### ISSUE TITLE
(27940) Login Failed, no redirect!

### ISSUE THREAD

**Issue by stsch83** [marvincaspar/ioBroker.sunnyportal#2]
**Describe the bug**  
Login Failed after a few hours.

**To Reproduce**  
1. start the instance
2. wait a few hours

**Expected behavior**  
I expect, that there is no login fail

**Versions:**  
 - Adapter version: 0.1.3
 - JS-Controller version: v10.19.0
 - Node version: v10.19.0

**Comment by marvincaspar** [comment]
This should be fixed in v0.1.5 which I published a few minutes ago
