### ISSUE TITLE
No data objectives created

### ISSUE THREAD

**Issue by ecomworld** [marvincaspar/ioBroker.sunnyportal#5]
I installed the adapter in Version 0.1.5 and I configured it with my credentials. The instance is green and the log file is not bringing up any errors.  
(14781) starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.sunnyportal, node: v10.19.0

Under objectives I only have the TimeStamp data object. Nothing else. (See screenshot)

![grafik](https://user-images.githubusercontent.com/52892823/79847958-b90fc780-83c0-11ea-9661-2bc05522a807.png)

As a hint where the problem could be, is that I have two plants ("Anlagen") in the sunny portal. Maybe there is the problem?

**Comment by marvincaspar** [comment]
It could be because you have more than one plant. I just have one plant, so I'm not able to test it. If you have some development skills, please feel free to debug the issue and maybe create a fix for it.

**Comment by ecomworld** [comment]
I deleted one of the plants, because it was an old one and now it works. Maybe you want to mention it in your readme.

**Comment by mcmuller** [comment]
Same here for me, but instead @ecomworld I have one plant with three devices (Inverter,webbox,repeater). Is this supported or not?

**Comment by marvincaspar** [comment]
this is currently not supported
